config/routes.rb
Rails.application.routes.draw do
  resources :categories, except: :show

  resources :products, path: '/'

  # Asi era la primera manera en como registramos las rutas
  #get '/products/new', to: 'products#new', as: :new_product
  #get '/products', to: 'products#index' # index me muestra un conjunto de productos
  # ~> el # me indica que es un metodo, y es alli donde definimos lo que me va
  # devolver el endpoint. (controlador)~>products#index~>(metodo)
  # por convencion la index me devuelve un conjunto de cosas
  # el metodo como nos devuelve algo, necesitamos declarar que es eso que me devuelve ( una vista)
  # M ~> Modelo
  # V ~> Vista
  # C ~> Controlador
  #get '/products/:id', to: 'products#show', as: :product
   # show me muestra un unico producto
   # 'as' hace referencia a un helper, y esto es un metodo que resuelve una ruta sin necesidad de declararla completa
  #post '/products', to: 'products#create'

  #delete '/products/:id', to: 'products#destroy'

  #patch '/products/:id', to: 'products#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :restrict_with_exception
end

app/models/product.rb
class Product < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_full_text, against: {
    title: 'A',
    description: 'B'
  }

  has_one_attached :photo

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true

  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  around_action :switch_locale

  def switch_locale(&action)
    I18n.with_locale(locale_from_header, &action)
  end

  private

  def locale_from_header
    request.env['HTTP_ACCEPT_LANGUAGE']&.scan(/^[a-z]{2}/)&.first
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all.order(name: :asc)
  end

  def new
    @category = Category.new
  end

  def edit
    category
  end

  def create
    @category = Category.new(category_params)

      if @category.save
        redirect_to categories_url, notice: t('.created')
      else
        render :new, status: :unprocessable_entity
      end
  end

  def update
      if category.update(category_params)
        redirect_to categories_url, notice: t('.updated')
      else
        render :edit, status: :unprocessable_entity
      end
  end


  def destroy
    category.destroy

    redirect_to categories_url, notice: t('.destroyed')
  end

  private
    def category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @categories = Category.order(name: :asc).load_async
    # TODO := investigar bien el async en rails

    @products = Product.all.with_attached_photo
    if params[:category_id]
      @products = @products.where(category_id: params[:category_id])
    end

    if params[:min_price].present?
      @products = @products.where("price >= ?", params[:min_price])
    end

    if params[:max_price].present?
      @products = @products.where("price <= ?", params[:max_price])
    end

    if params[:query_text].present?
      @products = @products.search_full_text(params[:query_text])
    end

    if params[:order_by].present?
      order_by = {
        "newest": "created_at DESC",
        "expensive": "price DESC",
        "cheapest": "price ASC"
      }.fetch(params[:order_by].to_sym, "created_at DESC")

      @products = @products.order(order_by)
    end
  end

  def show
    product
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_path, notice: t('.created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    product
  end

  def update
    if product.update(product_params)
      redirect_to products_path, notice: t('.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    product.destroy
    redirect_to products_path, notice: t('.destroyed'), status: :see_other
  end

  private

  def product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :description, :price, :photo, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
    <%= category.name %>
    <%= link_to t('.edit'), edit_category_path(category) %>
    <%= link_to t('.delete'), category_path(category), data: {
      turbo_method: :delete,
      turbo_confirm: t('.common.confirm')
      } 
    %>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% @category.errors.full_messages.each do |error| %>
    <div>
      <%= error %>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to t('common.back'), categories_path %>
</div>

app/views/categories/index.html.erb
<h1><%= t('.title') %></h1>

<%= render partial: 'category', collection: @categories %>

<%= link_to t('.new'), new_category_path %>

app/views/categories/new.html.erb
<h1><%= t('.title') %></h1>

<%= render "form", category: @category %>

<div>
  <%= link_to t('common.back'), categories_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vendelo | Compra y vende productos de segunda mano</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/flash' %>
    <%= render 'shared/header'%>
    <%= yield %>
  </body>
</html>

app/views/products/_category.html.erb
<%= link_to products_path(category_id: category.id), class: 'category' do %>
    <%= category.name %>
<% end %>

app/views/products/_form.html.erb
<%= form_with model: @product do |form| %>
    <% @product.errors.full_messages.each do |error| %>
        <div>
            <%= error %>
        </div>
    <% end %>

    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>

    <div>
        <%= form.label :description %>
        <%= form.text_area :description %>
    </div>

    <div>
        <%= form.label :price %>
        <%= form.number_field :price %>
    </div>

    <div>
        <%= form.label :category_id %>
        <%= form.collection_select :category_id, Category.all.order(name: :asc), :id, :name%>
    </div>

    <div>
        <%= form.label :photo %>
        <%= form.file_field :photo %>
    </div>
    <%= form.submit %>
<% end %>   

app/views/products/_product.html.erb
<div>
    <%= link_to product_path(product), class: 'product', 'data-turbo-frame': '_top' do %>
        <div>
            <%= image_tag product.photo, width: 100 if product.photo.attached? %>
        </div>

        <div>
            <h3><%= product.title %></h3>
            <span><%= product.price %>$</span>
            <%# cuando colocamos en el lenguaje de etiquetas el signo igual es porque necesito mostrar en mi pagina 
            el resultado del comando, cuando no lo hago esto se me proceso por debajo sin una salida por app web %>
        </div>
    <% end %>
</div>

app/views/products/edit.html.erb
<h2><%= t('.title') %></h2>

<%= render 'form' %>

app/views/products/index.html.erb
<%= turbo_frame_tag 'categories' do %>
    <h1><%= t('.title') %></h1>

    <%= form_with url: products_path, method: :get do |form| %>
        <%= form.text_field :query_text, placeholder: t('.query_search'), onChange: 'this.form.requestSubmit()', value: params[:query_text] %>
        <%= form.number_field :min_price, placeholder: t('.min_price'), onChange: 'this.form.requestSubmit()', value: params[:min_price] %>
        <%= form.number_field :max_price, placeholder: t('.max_price'), onChange: 'this.form.requestSubmit()', value: params[:max_price] %>
        <%= form.select :order_by, options_for_select([["Recientes", "newest"], ["Mas caros", "expensive"],
        ["Mas baratos", "cheapest"]], params[:order_by]), {}, { onChange: 'this.form.requestSubmit()' } %>
    <% end %>

    <%= link_to t('.all'), products_path %>

    <%= render partial: 'category', collection: @categories %> 

    <%= render partial: 'product', collection: @products %> <%# Investigar que hace esta linea de codigo %>
<% end %>

app/views/products/new.html.erb
<h2><%= t('.title')%></h2>

<%= render 'form'   %>

app/views/products/show.html.erb
<div>
    <%= image_tag @product.photo, width: 200 if @product.photo.attached? %>
</div>

<div>
    <h1 class='title'><%= @product.title %></h1>
    <p class='description'><%= @product.description %></p>
    <span class='price'><%= @product.price %>$</span>

    <%= link_to t('.edit'), edit_product_path(@product)%>

    <%= link_to t('.delete'), product_path(@product), data: {
        turbo_method: :delete,
        turbo_confirm: t('common.confirm')
    }%>
</div>

app/views/shared/_flash.html.erb
<%= notice %>
<%= alert  %>

app/views/shared/_header.html.erb
<%= link_to products_path do %>
    <h1>Vendelo</h1>
<% end %>

<%= link_to t('.add'), new_product_path %>
<%= link_to t('.categories'), categories_path %>